import type { ToolSet } from "./tool-set";

export type MainAgentTerminationReason =
  | "finished"
  | "maxStepsReached"
  | "error";

export type MainAgentInput = {
  systemPrompt: string;
  userPrompt: string;
  tools: ToolSet;
  maxSteps: number;
  /**
   * Heartbeat ID: a UUID generated by ProcessingCycle at the very start of
   * each cycle (before task selection). Used as the domain-scoped correlation
   * key for the `gen_ai.conversation.id` span attribute on the
   * `shrimp.main-agent` span. Not a session identifier; not persisted; isolated
   * per cycle.
   */
  heartbeatId: string;
};

export type MainAgentResult = {
  reason: MainAgentTerminationReason;
};

export interface MainAgent {
  run(input: MainAgentInput): Promise<MainAgentResult>;
}
