import type { ToolSet } from "./tool-set";

export type ShrimpAgentTerminationReason =
  | "finished"
  | "maxStepsReached"
  | "error";

export type JobInput = {
  systemPrompt: string;
  userPrompt: string;
  tools: ToolSet;
  maxSteps: number;
  /**
   * Job ID: a UUID generated by ProcessingCycle at the very start of
   * each cycle (before task selection). Used as the domain-scoped correlation
   * key for the `gen_ai.conversation.id` span attribute on the
   * `shrimp.main-agent` span. Not a session identifier; not persisted; isolated
   * per cycle.
   */
  jobId: string;
};

export type ShrimpAgentResult = {
  reason: ShrimpAgentTerminationReason;
};

export interface ShrimpAgent {
  run(input: JobInput): Promise<ShrimpAgentResult>;
}
