import type { ConversationMessage } from "../../entities/conversation-message";
import type { ToolSet } from "./tool-set";

export type ShrimpAgentTerminationReason =
  | "finished"
  | "maxStepsReached"
  | "error";

export type JobInput = {
  systemPrompt: string;
  userPrompt: string;
  tools: ToolSet;
  maxSteps: number;
  /**
   * Job ID: a UUID generated by Job at the very start of
   * each job (before task selection). Used as the domain-scoped correlation
   * key for the `gen_ai.conversation.id` span attribute on the
   * `shrimp.job` span. Not a session identifier; not persisted; isolated
   * per cycle.
   */
  jobId: string;
  /**
   * Conversation history preceding this invocation.
   * HeartbeatJob always passes an empty array.
   * ChannelJob passes the Session's prior messages so the agent
   * can maintain multi-turn context.
   */
  history: readonly ConversationMessage[];
  /**
   * Session identifier for ChannelJob only; absent for HeartbeatJob.
   * Passed through to the agent for telemetry purposes.
   */
  sessionId?: string;
};

export type ShrimpAgentResult = {
  reason: ShrimpAgentTerminationReason;
  /**
   * Assistant turn(s) produced during this invocation.
   * ChannelJob appends these to the Session after the agent returns.
   * HeartbeatJob ignores this field.
   */
  newMessages: readonly ConversationMessage[];
  /**
   * Prompt token count for the last step of this invocation, as reported
   * by the AI provider (ai.usage.promptTokens / gen_ai.usage.input_tokens).
   * Undefined when the provider does not report token usage — callers must
   * treat undefined as "skip compaction for this turn" (see SPEC §Auto Compact).
   */
  promptTokens: number | undefined;
};

export interface ShrimpAgent {
  run(input: JobInput): Promise<ShrimpAgentResult>;
}
